name: Deploy + Lighthouse

on:
   push:
     branches: [main, dev, staging]
   pull_request:
     branches: [main, dev, staging]

jobs:
  # :one: Build + Deploy Job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install
      - run: npm run build
      - name: Deploy to Vercel
        run: npx vercel --yes --token=${{ secrets.VERCEL_TOKEN }} 


  #  Lighthouse Job – waits for deployment_status.success
  lighthouse:
    needs: [deploy]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install @lhci/cli@0.15.x
      - run: npm run  build
      - run: npm run lighthouse 
        env:
          LHCI_URL: ${{ steps.get-vercel-preview-url.outputs.preview_url }}
          LHCI_START: npm run start
          