name: Deploy + Lighthouse
on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]
jobs:
  # :one: Build + Deploy Job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run build
      - name: Deploy to Vercel
        id: vercel-deploy
        run: |
          url=$(npx vercel --yes --token=${{ secrets.VERCEL_TOKEN }} --yes )
          echo "preview_url=$url" >> $GITHUB_OUTPUT
      - name: Run Lighthouse on Preview
        run: |
         echo "Testing: ${{ steps.vercel-deploy.outputs.preview_url }}"
         pnpm lhci autorun --collect.url=${{ steps.vercel-deploy.outputs.preview_url }}
  # :two: Lighthouse Job – waits for deploy, then runs against preview URL
  